server:
  port: 8088
spring:
  datasource:
    # 数据源设置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/studentx_db?serverTimezone=UTC
      username: "root"
      password: "123456"
  banner:
    location: banner

mybatis-plus:
  global-config:
    db-config:
      # 表前缀
      table-prefix: tbl_
      # id自增策略
      id-type: auto
    banner: false
  configuration:
    # MP调试日志标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  # 签名秘钥
  sign-key: "studentx"
  # 有效期
  expiration: 2592000000


