server:
  # 端口
  port: 80

spring:
  # 数据库连接配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库地址
      url: jdbc:mysql://localhost:3306/stux_db?serverTimezone=UTC
      # 数据库用户名
      username: "root"
      # 数据库密码
      password: "toor"

mybatis-plus:
  global-config:
    db-config:
      # 表前缀
      table-prefix: tbl_
      # id自增策略
      id-type: auto
  configuration:
    # MP调试日志标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



